Fix `dbg_xlate_linear2phy` for NPT
stlintel/Bochs pull request #30
Opened 2022-08-19 04:37 UTC by tandasat

`dbg_xlate_linear2phy()` does not translate the guest physical address for a AMD processor. This prevents the Bochs debugger from displaying memory contents and disassembled code when the processor is running in the guest mode, making it quite useless.

This patch fixes this by enabling translation by calling `dbg_translate_guest_physical` . `dbg_translate_guest_physical` was updated to get nCr3 and check PTEs with a different bitmask when the translation is being done for AMD. 

Focus on the 2nd commit for review.

2022-08-19 04:40 UTC, tandasat commented on bochs/cpu/paging.cc
> +#endif
This refactoring was done to avoid duplicating those condition checks 3 times. 
```c
#if BX_SUPPORT_VMX >= 2
   // (Condition check for VMX) {
     if (! dbg_translate_guest_physical(pt_address, &pt_address, verbose))
       goto page_fault;
  }
#endif
#if BX_SUPPORT_SVM
   // (Condition check for SVM) {
     if (! dbg_translate_guest_physical(pt_address, &pt_address, verbose))
       goto page_fault;
  }
#endif
```

2022-08-19 04:42 UTC, tandasat commented on bochs/cpu/cpu.h
> -#endif
Now this function is compiled unconditionally. It is never called if neither SVM or VMX>2 enabled.

2022-08-19 04:48 UTC, tandasat commented on bochs/cpu/paging.cc
> +        return 0;
The layout of the NTP entry is identical to the standard PTE. Meaning that only when missing the bit 0, it is unreadable.

2022-08-20 09:03 UTC, stlintel reviewed
Please split non-functional changes (like whitespace cleanup) from functional PR

2022-08-20 09:06 UTC, stlintel requested changes

2022-08-20 09:06 UTC, stlintel commented on bochs/cpu/cpu.h
> -#endif
May be better to compile it if VMX >= 2 || SVM

2022-08-20 09:06 UTC, stlintel commented on bochs/cpu/paging.cc
> +#else
if compiled for VMX || SVM there will be no else

2022-08-20 15:35 UTC, tandasat commented on bochs/cpu/paging.cc
> +#else
Not sure if I followed but the code around it has changed.

2022-08-20 15:53 UTC, tandasat commented
> Please split non-functional changes (like whitespace cleanup) from functional PR

I dropped the commit.

Can you explain what is the reason for this rule? IMO, this should be allowed, as long as such changes are separated from functional change commits..

To my knowledge, not leaving trailing spaces is a common practice, and so, many of developers configure their editors to auto-delete trailing spaces. This rule (not mixing functional & non-functional changes) will be annoyance to contribute to this projects for many, and passively encourage contributors leave trailing spaces (for example, I am not going to create a PR for only removing trailing spaces).
  
GitHub allows reviewing select commits, and we can revert functional-commits and leave trailing space removal commits if needed. I do not see much benefit of the rule.

2022-08-20 15:57 UTC, tandasat commented on bochs/cpu/cpu.h
> -#endif
Resolved in [0bcfcb0](https://github.com/stlintel/Bochs/pull/30/commits/0bcfcb062c22de6984bfa07ae906390beccb8cb2)

2022-08-20 17:51 UTC, stlintel commented
It is very hard to follow what are the functional changes and what are just whitespace.
If there are small amount of whitespace changes it is easy to follow but with 9/10 of the PR - it is very inconvenient.
You could just submit single PR with whitespace cleanups in entire CPU code if you want, it will be accepted.

2022-08-20 18:08 UTC, stlintel commented
Actually your entire patch is under assumption that SVM is using long mode PAE mode for nested walk
Which is incorrect assumption.
Nested walk could be long mode, PAE or even legacy walk.
At the end I suggest to drop the PR and rewrite it properly to support all SVM vases or at least print nicely when dbg walk is not supported / not implemented yet

2022-08-20 18:12 UTC, stlintel commented
BTW - you may notice that nested walk is just the same as regular walk in x86 just starting from another base
So might be the best way is to reuse existing dbg_xlate_linear2phy may be adding a parameter to it saying it is nested walk
The parameter will prevent even deeper nested walk and do smarter verbose prints.

2022-08-21 04:32 UTC, tandasat commented
Good catch on the paging mode, and thanks for the idea of reusing dbg_xlate_linear2phy. I will look into it and/or showing warning. I may scrap this PR and recreate a new one, or may just remove previous commits.

I might create the mass trailing space removal PR for `cpu`, or even better, all source files if that is acceptable.

2022-08-21 08:08 UTC, therealdreg commented
> I might create the mass trailing space removal PR for `cpu`, or even better, all source files if that is acceptable.

If we will change all the source code for cosmetic reasons, (btw I'm not sure if this is a good idea). 

We could take this opportunity to force and fix the coding style of the whole project with an automatic tool like clang-tidy. 

clang-tidy does a deeper inspection and can be used to flag things that are "bad practice", not just "bad formatting". This would help to have more consistency.

But as I said, I'm not sure if it is a good idea modify all the source code :\

2022-08-21 08:34 UTC, stlintel commented
I thought about it but I am not a master to configure the tool anyway.
Also forcing people to specific very strict style is not a way to go in my opinion.
But obvious bad style should be fixed.

2022-08-21 19:14 UTC, stlintel requested changes

2022-08-21 19:14 UTC, stlintel commented on bochs/cpu/paging.cc
> +      if (! dbg_translate_guest_physical_with_ept(paddress, &paddress, verbose))
Looks nice, just some naming ...

Could you rename 
dbg_translate_guest_physical_with_ept -> dbg_translate_guest_physical_ept
dbg_translate_guest_physical_with_npt -> dbg_translate_guest_physical_npt
second_level_translation => nested_walk

2022-08-21 19:16 UTC, tandasat commented
Update the PR to reuse `dbg_xlate_linear2phy`. Dropped previous commits.

Mass deletion of trailing spaces should not be really controversial. Setting up something to prevent addition of trailing spaces (eg, `.editorconfig`) and to enforce other coding styles (eg, `.clang-format`) are. Let us create their own issues and discuss there.

2022-08-21 19:16 UTC, tandasat commented on bochs/cpu/paging.cc
> +      if (! dbg_translate_guest_physical_with_ept(paddress, &paddress, verbose))
will do.

2022-08-21 19:47 UTC, tandasat commented on bochs/cpu/paging.cc
> +      if (! dbg_translate_guest_physical_with_ept(paddress, &paddress, verbose))
Fixed with 179c95d

2022-08-22 04:20 UTC, stlintel approved these changes

2022-08-22 04:20 UTC, merged