add new dbg command loadmem, load bytes from file to memory (laddr)
stlintel/Bochs pull request #34
Opened 2022-08-21 11:45 UTC by therealdreg

add new dbg command loadmem, load bytes from file to memory (laddr)

![loadmem poc](https://user-images.githubusercontent.com/9882181/185789304-cac1264a-6ff6-45ef-b602-837a876f0119.png)

Like GDB style:

- writemem to dump memory to file
- edit file
- load modified file to memory using the new command: **loadmem**

2022-08-21 13:08 UTC, stlintel requested changes

2022-08-21 13:08 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +      bytes_readed = fread(databuf, 1, sizeof(databuf), f);
Sorry for collecting english grammar - bytes_readed is not english
should be bytes_read

2022-08-21 13:08 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +  Bit8u databuf[4096];
why databuf is 4096 ?

2022-08-21 13:08 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +        for (size_t i = 0; i < bytes_readed; i++, laddr++) {
I see laddr is not necessary 4K aligned so it could spawn 2 pages
this is why you have to re-translate every byte ?
It would be better to handle it on 4K blocks which first block might be smaller if laddr if not 4K aligned.
And translate lin2phy only once for each block.

2022-08-21 13:15 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  Bit8u databuf[4096];
Because writemem use the same thing xD

2022-08-21 13:15 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +      bytes_readed = fread(databuf, 1, sizeof(databuf), f);
fixed!

2022-08-21 13:18 UTC, stlintel commented
Also please not include in the patch automatically generated files for parser and lexer

2022-08-21 13:21 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  Bit8u databuf[4096];
![image](https://user-images.githubusercontent.com/9882181/185792849-2e9196d0-a834-4e6a-a028-d837ba3e4d6d.png)

For me makes sense use the same size chunk (page)

2022-08-21 13:23 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  Bit8u databuf[4096];
> Also please not include in the patch automatically generated files for parser and lexer

ok, removed!

2022-08-21 13:24 UTC, therealdreg commented
> Also please not include in the patch automatically generated files for parser and lexer

Oki, removed!

2022-08-21 13:24 UTC, stlintel requested changes

2022-08-21 13:24 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +  size_t bytes_readed = 0;
I see it is still bytes_readed ? :)

2022-08-21 13:25 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  size_t bytes_readed = 0;
F5 please

2022-08-21 13:29 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +        for (size_t i = 0; i < bytes_readed; i++, laddr++) {
> this is why you have to re-translate every byte ?

Exactly, I was not sure what is the best way and byte_x_byte works fine hehe

2022-08-21 13:34 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +        for (size_t i = 0; i < bytes_readed; i++, laddr++) {
> > this is why you have to re-translate every byte ?
> 
> Exactly, I was not sure what is the best way and byte_x_byte works fine hehe

I had smth similar implemented in my private version and it is visible slow already when loading complete memory dumps of few hundreds of MB

2022-08-21 13:39 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +        for (size_t i = 0; i < bytes_readed; i++, laddr++) {
@stlintel my current code works fine (its secure, but not fast. For this feature speed its not a priority imo). If I change this its possible have problems in some scenarios with different page sizes? (4 KiB, 2 MiB, 1 GiB)

2022-08-21 13:41 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +        for (size_t i = 0; i < bytes_readed; i++, laddr++) {
I don't ask anything crazy, just use blocks of 4KB
Translate once - new you could write to memory up to end of the current 4KB page or whole page if was 4K aligned.

2022-08-21 13:46 UTC, stlintel commented
You may use bx_dbg_read_linear as example
What you want to write is actually bx_dbg_write_linear or similar

2022-08-21 13:47 UTC, therealdreg commented
> bx_dbg_write_linear

Oka, working in it...

2022-08-21 14:08 UTC, therealdreg commented
> You may use bx_dbg_read_linear as example What you want to write is actually bx_dbg_write_linear or similar

done, take a look to final version

2022-08-21 14:09 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +        for (size_t i = 0; i < bytes_readed; i++, laddr++) {
done!

2022-08-21 14:32 UTC, therealdreg commented
Resolved conflicts with setpmem8 :D

2022-08-21 15:54 UTC, stlintel requested changes

2022-08-21 15:54 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +  fseek(f, 0L, SEEK_END);
could you extract taking the length of a file to a function ?
In case some platform doesn't like fseek and ftell it will be much easier to w/a the issue.

2022-08-21 15:54 UTC, stlintel commented on bochs/bx_debug/dbg_main.cc
> +  dbg_printf("Writing 0x%lx bytes from %s to " FMT_ADDRX "\n", ftell(f), filename);
The printf is incorrect, missing parameter for address

2022-08-21 15:54 UTC, stlintel commented on bochs/bx_debug/parser.y
> +	| loadmem_command
please align the code properly

2022-08-21 21:27 UTC, therealdreg commented on bochs/bx_debug/parser.y
> +	| loadmem_command
done!

2022-08-21 21:29 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  dbg_printf("Writing 0x%lx bytes from %s to " FMT_ADDRX "\n", ftell(f), filename);
Oh, sorry, fixed

2022-08-21 21:29 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  fseek(f, 0L, SEEK_END);
done!

2022-08-21 21:32 UTC, therealdreg commented
All suggestions done. Thank you for your patience, it's a pleasure working with you :D 

@stlintel its good for you. now?

2022-08-21 21:44 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  fseek(f, 0L, SEEK_END);
I removed fseek calls and keep ftell() call, its is good for you?

2022-08-21 22:00 UTC, therealdreg commented on bochs/bx_debug/dbg_main.cc
> +  fseek(f, 0L, SEEK_END);
Removed ftell and fseek part :D

2022-08-22 04:23 UTC, stlintel approved these changes

2022-08-22 04:24 UTC, stlintel commented
Approved.
I let you do the Squash and merge to make sure it works from user side too.

2022-08-22 04:26 UTC, therealdreg commented
> Approved. I let you do the Squash and merge to make sure it works from user side too.

mm I dont have rights in your repo I think. I cant merge :\

2022-08-22 05:17 UTC, merged